### ISSUE TITLE
Intermittent error - Uable to find Index.cshtml

### ISSUE THREAD

**Issue by hflateland** [Altinn/app-lib-dotnet#160]
### Description of the bug

Error happend when running local test on Windows machine.

App was created yesterday.  When trying to start the app from local test the following error occured:

![image](https://user-images.githubusercontent.com/44457738/211822952-ac8ffee0-e7a8-42b9-84ad-da3bf97b7472.png)

When renaming the folder containing Home\Index.cshtml from "views" to "Views" the schema loaded as normal.   I have not been able the recreate the error since, and the schema works now even when renaming the folder back to "views".  

### Steps To Reproduce

-

### Additional Information

-

**Comment by TheTechArch** [comment]
Are you running localtest with dotnet run or in docker?

**Comment by hflateland** [comment]
Dotnet run

**Comment by olemartinorg** [comment]
Linux/mac uses a case-sensitive file system, while Windows is case-insenitive.

Sounds a bit strange that it worked with a mixed-case `Views`, when all other apps I have running here on my Linux machine work with an all-lowercase `views`.

I suspect this might have been some sort of caching issue instead, which got invalidated when you renamed the folder. The fact that it now works with both variants suggest you are running Windows, but beware that uppercasing `Views` might not work when running on Linux (in ex. `tt02`).

**Comment by hflateland** [comment]
Same happend on a new schema created today, never started before locally.

dotnet run on Windows machine

![image](https://user-images.githubusercontent.com/44457738/212055955-b43ff350-55a8-4076-8606-9deec789bc54.png)

**Comment by olemartinorg** [comment]
Just to make sure, did both of these happen as soon as you tried to open LocalTest, or did the problems manifest when you clicked 'Proceed to app'? From the first screenshot I cannot see the URL, but from the last screenshot it seems this happened in the app itself (meaning you clicked 'Proceed to app' first).

I also notice you're using `altinn3local.no`. We switched to using `local.altinn.cloud` a few months ago - have you updated your clone of `altinn-studio` to make sure you're using the latest version of LocalTest? If not, please do. That might not be the cause of your problems, but it certainly won't help anything.

**Comment by hflateland** [comment]
It happend when pressing "Proceed to app".  Did a 'dotnet clean' afterwards and that fixed the issue.

It's a while since I did a 'git pull' on altinn-studio, so did it now.  Will let you know if I get any more cases, but this is not a critical issue for my part.

**Comment by hflateland** [comment]
Happend again.  'dotnet clean' solved the problem.    

* Using latest altinn-studio
* Using latest dockers
* Using local.altinn.cloud


```
$ dotnet run
CSC : warning RSG002: TargetPath not specified for additional file: C:\Users\hafl\Documents\Vscode\bli-verge\app\views\Home\Index.cshtml. [C:\Users\hafl\Documents\Vscode\bli-verge\app\App.csproj]
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Overriding address(es) 'http://localhost:56227/'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:5005
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\hafl\Documents\Vscode\bli-verge\app\
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://host.docker.internal:5005/dummyOrg/dummyApp/api/v1/applicationmetadata?checkOrgApp=false - -
dbug: AltinnCore.Authentication.JwtCookie.JwtCookieHandler[9]
      AuthenticationScheme: JwtCookie was not authenticated.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Altinn.App.Api.Controllers.ApplicationMetadataController.GetAction (Altinn.App.Api)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "GetAction", controller = "ApplicationMetadata"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult GetAction(System.String, System.String, Boolean) on controller Altinn.App.Api.Controllers.ApplicationMetadataController (Altinn.App.Api).
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Executing action method Altinn.App.Api.Controllers.ApplicationMetadataController.GetAction (Altinn.App.Api) - Validation state: Valid
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action method Altinn.App.Api.Controllers.ApplicationMetadataController.GetAction (Altinn.App.Api), returned result Microsoft.AspNetCore.Mvc.OkObjectResult in 208.7256ms.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      Executing OkObjectResult, writing value of type 'Altinn.Platform.Storage.Interface.Models.Application'.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action Altinn.App.Api.Controllers.ApplicationMetadataController.GetAction (Altinn.App.Api) in 319.1943ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Altinn.App.Api.Controllers.ApplicationMetadataController.GetAction (Altinn.App.Api)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://host.docker.internal:5005/dummyOrg/dummyApp/api/v1/applicationmetadata?checkOrgApp=false - - - 200 - application/json;+charset=utf-8 518.8110ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://host.docker.internal:5005/srf/bli-verge/testData.json - -
dbug: AltinnCore.Authentication.JwtCookie.JwtCookieHandler[9]
      AuthenticationScheme: JwtCookie was not authenticated.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://host.docker.internal:5005/srf/bli-verge/testData.json - - - 404 0 - 7.4659ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://host.docker.internal:5005/srf/bli-verge/api/v1/meta/authorizationpolicy - -
dbug: AltinnCore.Authentication.JwtCookie.JwtCookieHandler[9]
      AuthenticationScheme: JwtCookie was not authenticated.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Altinn.App.Api.Controllers.ApplicationMetadataController.GetPolicy (Altinn.App.Api)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "GetPolicy", controller = "ApplicationMetadata"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult GetPolicy(System.String, System.String) on controller Altinn.App.Api.Controllers.ApplicationMetadataController (Altinn.App.Api).
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Executing action method Altinn.App.Api.Controllers.ApplicationMetadataController.GetPolicy (Altinn.App.Api) - Validation state: Valid
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action method Altinn.App.Api.Controllers.ApplicationMetadataController.GetPolicy (Altinn.App.Api), returned result Microsoft.AspNetCore.Mvc.ContentResult in 2.7814ms.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ContentResultExecutor[1]
      Executing ContentResult with HTTP Response ContentType of text/xml; charset=utf-8
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action Altinn.App.Api.Controllers.ApplicationMetadataController.GetPolicy (Altinn.App.Api) in 9.1173ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Altinn.App.Api.Controllers.ApplicationMetadataController.GetPolicy (Altinn.App.Api)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://host.docker.internal:5005/srf/bli-verge/api/v1/meta/authorizationpolicy - - - 200 21623 text/xml;+charset=utf-8 21.1083ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://host.docker.internal:5005/dummyOrg/dummyApp/api/v1/applicationmetadata?checkOrgApp=false - -
dbug: AltinnCore.Authentication.JwtCookie.JwtCookieHandler[9]
      AuthenticationScheme: JwtCookie was not authenticated.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Altinn.App.Api.Controllers.ApplicationMetadataController.GetAction (Altinn.App.Api)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "GetAction", controller = "ApplicationMetadata"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult GetAction(System.String, System.String, Boolean) on controller Altinn.App.Api.Controllers.ApplicationMetadataController (Altinn.App.Api).
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Executing action method Altinn.App.Api.Controllers.ApplicationMetadataController.GetAction (Altinn.App.Api) - Validation state: Valid
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action method Altinn.App.Api.Controllers.ApplicationMetadataController.GetAction (Altinn.App.Api), returned result Microsoft.AspNetCore.Mvc.OkObjectResult in 0.0145ms.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      Executing OkObjectResult, writing value of type 'Altinn.Platform.Storage.Interface.Models.Application'.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action Altinn.App.Api.Controllers.ApplicationMetadataController.GetAction (Altinn.App.Api) in 1.4545ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Altinn.App.Api.Controllers.ApplicationMetadataController.GetAction (Altinn.App.Api)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://host.docker.internal:5005/dummyOrg/dummyApp/api/v1/applicationmetadata?checkOrgApp=false - - - 200 - application/json;+charset=utf-8 2.0925ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://host.docker.internal:5005/srf/bli-verge/testData.json - -
dbug: AltinnCore.Authentication.JwtCookie.JwtCookieHandler[9]
      AuthenticationScheme: JwtCookie was not authenticated.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://host.docker.internal:5005/srf/bli-verge/testData.json - - - 404 0 - 0.4233ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://host.docker.internal:5005/srf/bli-verge/api/v1/applicationmetadata?checkOrgApp=false - -
dbug: AltinnCore.Authentication.JwtCookie.JwtCookieHandler[9]
      AuthenticationScheme: JwtCookie was not authenticated.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Altinn.App.Api.Controllers.ApplicationMetadataController.GetAction (Altinn.App.Api)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "GetAction", controller = "ApplicationMetadata"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult GetAction(System.String, System.String, Boolean) on controller Altinn.App.Api.Controllers.ApplicationMetadataController (Altinn.App.Api).
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Executing action method Altinn.App.Api.Controllers.ApplicationMetadataController.GetAction (Altinn.App.Api) - Validation state: Valid
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action method Altinn.App.Api.Controllers.ApplicationMetadataController.GetAction (Altinn.App.Api), returned result Microsoft.AspNetCore.Mvc.OkObjectResult in 0.0162ms.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      Executing OkObjectResult, writing value of type 'Altinn.Platform.Storage.Interface.Models.Application'.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action Altinn.App.Api.Controllers.ApplicationMetadataController.GetAction (Altinn.App.Api) in 0.5111ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Altinn.App.Api.Controllers.ApplicationMetadataController.GetAction (Altinn.App.Api)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://host.docker.internal:5005/srf/bli-verge/api/v1/applicationmetadata?checkOrgApp=false - - - 200 - application/json;+charset=utf-8 0.9585ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.0 GET http://local.altinn.cloud/srf/bli-verge/ - -
info: AltinnCore.Authentication.JwtCookie.JwtCookieHandler[0]
      Successfully validated the token.
dbug: AltinnCore.Authentication.JwtCookie.JwtCookieHandler[8]
      AuthenticationScheme: JwtCookie was successfully authenticated.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Altinn.App.Api.Controllers.HomeController.Index (Altinn.App.Api)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index(System.String, System.String, Boolean) on controller Altinn.App.Api.Controllers.HomeController (Altinn.App.Api).
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Executing action method Altinn.App.Api.Controllers.HomeController.Index (Altinn.App.Api) - Validation state: Valid
fail: Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery[7]
      An exception was thrown while deserializing the token.
      Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
       ---> System.Security.Cryptography.CryptographicException: The payload was invalid. For more information go to http://aka.ms/dataprotectionwarning
         at Microsoft.AspNetCore.DataProtection.Cng.CbcAuthenticatedEncryptor.DecryptImpl(Byte* pbCiphertext, UInt32 cbCiphertext, Byte* pbAdditionalAuthenticatedData, UInt32 cbAdditionalAuthenticatedData)
         at Microsoft.AspNetCore.DataProtection.Cng.Internal.CngAuthenticatedEncryptorBase.Decrypt(ArraySegment`1 ciphertext, ArraySegment`1 additionalAuthenticatedData)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action method Altinn.App.Api.Controllers.HomeController.Index (Altinn.App.Api), returned result Microsoft.AspNetCore.Mvc.PartialViewResult in 148.1382ms.
info: Microsoft.AspNetCore.Mvc.ViewFeatures.PartialViewResultExecutor[1]
      Executing PartialViewResult, running view Index.
fail: Microsoft.AspNetCore.Mvc.ViewFeatures.PartialViewResultExecutor[3]
      The partial view 'Index' was not found. Searched locations: /Views/Home/Index.cshtml, /Views/Shared/Index.cshtml
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action Altinn.App.Api.Controllers.HomeController.Index (Altinn.App.Api) in 189.0308ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Altinn.App.Api.Controllers.HomeController.Index (Altinn.App.Api)'
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: The view 'Index' was not found. The following locations were searched:
      /Views/Home/Index.cshtml
      /Views/Shared/Index.cshtml
         at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.PartialViewResultExecutor.ExecuteAsync(ActionContext context, PartialViewResult result)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|22_0(ResourceInvoker invoker, IActionResult result)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.0 GET http://local.altinn.cloud/srf/bli-verge/ - - - 500 - text/html;+charset=utf-8 1201.6445ms
```

![image](https://user-images.githubusercontent.com/44457738/212072989-8e8eb485-d05c-40df-8103-5f59a4a7491a.png)
