### ISSUE TITLE
LocalTest with Podman on port 8000 fails when generating PDF

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-lib-dotnet#436]
### Description of the bug

When trying to run v7 with the new Podman setup where we run on `local.altinn.cloud:8000`, the PDF generation fails every time with:

```
fail: Altinn.App.Api.Controllers.ProcessController[0]
      Process next failed.
      Altinn.App.Core.Internal.Pdf.PdfGenerationException: Pdf generation failed
         at Altinn.App.Core.Infrastructure.Clients.Pdf.PdfGeneratorClient.GeneratePdf(Uri uri, CancellationToken ct)
         at Altinn.App.Core.Internal.Pdf.PdfService.GenerateAndStorePdf(Instance instance, CancellationToken ct)
         at Altinn.App.Core.Implementation.DefaultTaskEvents.RunLockDataAndGeneratePdf(String endEvent, Instance instance, List`1 dataTypesToLock)
         at Altinn.App.Core.Implementation.DefaultTaskEvents.OnEndProcessTask(String endEvent, Instance instance)
         at Altinn.App.Core.Internal.Process.Elements.DataTask.HandleTaskComplete(ProcessChangeContext processChangeContext)
         at Altinn.App.Core.Internal.Process.ProcessChangeHandler.HandleProcessChanges(ProcessChangeContext processChangeContext)
         at Altinn.App.Core.Internal.Process.ProcessChangeHandler.UpdateProcessAndDispatchEvents(ProcessChangeContext processChangeContext)
         at Altinn.App.Core.Internal.Process.ProcessChangeHandler.HandleMoveToNext(ProcessChangeContext processChange)
         at Altinn.App.Core.Internal.Process.ProcessEngine.Next(ProcessChangeContext processChange)
         at Altinn.App.Api.Controllers.ProcessController.NextElement(String org, String app, Int32 instanceOwnerPartyId, Guid instanceGuid, String elementId, String lang)
```

This makes our Cypress tests on app-frontend v3 (with backend v7) 

### Steps To Reproduce

1. Open `ttd/frontend-test-v3`
2. Generate a PDF (i.e. run the `all-process-steps.ts` Cypress test)
3. Observe it failing pretty much immediately

**Comment by olemartinorg** [comment]
Same goes for v8, apparently

**Comment by tjololo** [comment]
Tested my test application with v3/v7, v3/v8 and v4/v8 combination and it seems to work (stopped the old pdf service just to be sure) with localtest running with Podman on port 8000. Can you see any error logs in the `altinn-pdf-service` container?

**Comment by olemartinorg** [comment]
Huh, strange! I might have just assumed this was a general problem. Logs say:

```
2024-02-09T15:51:32.644Z browserless:job 5KC096I55X7PVX3Y27U3G0SKUENN8O9V: Function errored, stopping Chrome: Error: net::ERR_CONNECTION_REFUSED at http://local.altinn.cloud/ttd/frontend-test-v3/#/instance/512345/b73d93a7-08ee-4c47-9c33-d9ca2016f40b?pdf=1&lang=nb
    at navigate (/usr/src/app/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Frame.js:235:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Frame.goto (/usr/src/app/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Frame.js:205:21)
    at async CDPPage.goto (/usr/src/app/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:1053:16)
2024-02-09T15:51:32.644Z browserless:server 5KC096I55X7PVX3Y27U3G0SKUENN8O9V: Recording failed stat, cleaning up: "net::ERR_CONNECTION_REFUSED at http://local.altinn.cloud/ttd/frontend-test-v3/#/instance/512345/b73d93a7-08ee-4c47-9c33-d9ca2016f40b?pdf=1&lang=nb"
```

Might be a configuration error then. I didn't find any obvious place I should set to `local.altinn.cloud:8000` in that case. I tried changing the values I found in `appsettings.json` but I might have just messed it up. I'll try again.

**Comment by tjololo** [comment]
Intenally in the "podman/docker"-network the loadbalancer still runs on port 80 so there should be no need to override the address sent to puppeteer. The address "local.altinn.cloud is also an alias for localtest-loadbalancer if not it would resolve to 127.0.0.1 pointing puppeteer back to itself. Lets schedule a debug session on monday if you are available?

**Comment by olemartinorg** [comment]
No need to rush this one, btw. I believe now that it's caused by some DNS service not working on my linux machine - as the alias in the podman network doesn't seem to kick in. I'll debug that myself when I get around to it.

**Comment by RonnyB71** [comment]
Closing this one assuming it's a issue on @olemartinorg laptop. Just re-open if this is not the case.
